### ISSUE TITLE
SSMSTool.dll - Where is it?

### ISSUE THREAD

**Issue by PublicRadioCorgi** [alekseybochkov/ssms-addin#1]
Hi There:

Firstly, thank you very much for this addin. It looks like it could be quite useful for me. 

Unfortunately, I cannot figure out where the SSMSTool.dll file is located. The readme file says I have to modify SSMSTool.AddIn with the path to  SSMSTool.dll - but I have no such file. Is the dll supposed to be in the repository? Or do I have to make that file somehow?

Sorry if these are noob questions, I am not very experienced with SSMS addins. 

Thanks!

**Comment by alex-bochkov** [comment]
Hi @graciecorgi,

You may find `SSMSTool.dll` file in releases: https://github.com/alekseybochkov/ssms-addin/releases

**Comment by alex-bochkov** [comment]
I've released new addin for SSMS 2018.
